### ISSUE TITLE
Python development page needs updates

### ISSUE THREAD

**Issue by natashadsilva** [ibm-cloud-docs/StreamingAnalytics#4]
https://cloud.ibm.com/docs/services/StreamingAnalytics?topic=StreamingAnalytics-t_develop_apps_python

Healthcare demo has been removed from watson studio
Python course has been deleted from Developer works

After running Hello, World, the Rolling average sample is now the best getting started example that can be used in Cloud Pak for Data or Watson Studio. https://github.com/IBMStreams/sample.starter_notebooks/blob/master/Streams-RollingAverageSample.ipynb

**Comment by natashadsilva** [comment]
@orzade

**Comment by natashadsilva** [comment]
@pvallen

**Comment by pvallen** [comment]
@natashadsilva I'll remove the references to healthcaredemo and the python course at the bottom.

Since the rolling average article is written specifically for Cloud Pak for Data, that wouldn't be appropriate for the public cloud. Would it be possible to use the same notebook with a new article to use with Streaming Analytics?

**Comment by natashadsilva** [comment]
@pvallen the rolling average sample was updated to have descriptions for both public cloud and cloudpak for data, see section 1 and 1.1.a/b.

**Comment by pvallen** [comment]
This change is published in production.
